//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Hotel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime DepartureDate { get; set; }
        public int ClientID { get; set; }
        public int UserID { get; set; }
        public int RoomID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Room Room { get; set; }
    }
}
