//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Hotel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int ID { get; set; }
        public int Number { get; set; }
        public int FloorID { get; set; }
        public int CategoryID { get; set; }
        public int StatusID { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Category Category { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Status Status { get; set; }
    }
}
